### ISSUE TITLE
params in sql and paging

### ISSUE THREAD

**Issue by huahuayu** [sohangp/spring-data-jpa-projections-example#1]
hi, I have read your medium [post](https://medium.com/swlh/spring-data-jpa-projection-support-for-native-queries-a13cd88ec166) about this project, and run the project, it's great to put native query in orm.xml and map two tables. 

But for real-world cases, queries often have params and the result need paging, how to do it with JPA-projection,  would you please make the example go deeper?

I have a complex sql as below, the `beenUsed` field is neither from a nor b table, how do I mapping it to a dto?

``` sql
    select
        a.*,
        (case
            when count(b.rule_id) > 0 then 'Y'
            else 'N'
        end) beenUsed
    from
        t_rule a
    left join
        t_ruleset_rule_rel b
            on a.id = b.rule_id
    where
        if(? is not null ,a.name like concat('%',?,'%') ,1=1)
        and if(? > 0 ,a.type in (?, ?) ,1=1)
        and if(? is not null ,a.create_time >= ? ,1=1)
        and if(? is not null ,a.create_time <= ? ,1=1)
    group by
        a.id
    order by
        a.create_time desc limit ?
```

currently, I write sql like this, but get syntax error, would you please give some suggestion?

``` java
    @Query(value = "select new com.coolproject.dto.RuleRec(a.id as id,a.name as name, a.desc as desc, a.type as type, a.value as value, a.status as status, a.create_time as createTime, a.create_user as createUser, a.update_time as updateTime, a.update_user as updateUser, (case when count(b.rule_id) > 0 then 'Y' else 'N' end) as beenUsed) " +
            "from t_rule a left join t_ruleset_rule_rel b on a.id = b.rule_id where " +
            "if(:#{#param.name} is not null ,a.name like concat('%',:#{#param.name},'%') ,1=1) " +
            "and if(:#{#param.type.size()} > 0 ,a.type in :#{#param.type} ,1=1)" +
            "and if(:#{#param.startDate} is not null ,a.create_time >= :#{#param.startDate} ,1=1) " +
            "and if(:#{#param.endDate} is not null ,a.create_time <= :#{#param.endDate} ,1=1) " +
            "group by a.id", nativeQuery = true)
    Page<RuleRec> ruleRecList(@Param("param") RuleQueryParam param, Pageable pageable);
```

**Comment by sohangp** [comment]
Hello thanks for the feedback !

### Complex Query
Having a complex select is easy, as mentioned in the post you can mirror the result-set fetched to the DTO using the `as` keyword in you SQL query providing an alias. The alias maps the accessor method defined in the DTO.

Like in the example given in the blog
**Query:** 
``` sql
select
   cust.id as customerId,
```
in the **DTO**
``` java
Integer getCustomerId();
```
the Alias and the  accessor method defined has to be the same.

### Query Parameters
For sending parameters to the SQL query, I have added a new search method which takes in a param from the REST controller and searches for a customer based on a firstName.

**Service layer:** 
``` java
    public List<CustomerDetailsDTO> searchCustomerByFirstName(String firstName) throws  Exception {
        return customerRepository.searchCustomerByFirstName(firstName);
    }
```

**DAO layer:**  
``` java
    @Query(name = "customerEntity.searchCustomerByFirstName", nativeQuery = true)
    List<CustomerDetailsDTO> searchCustomerByFirstName(@Param("firstName") String firstName);
```

**SQL Query on orm.xml:** 
``` sql
            SELECT
                cust.id as customerId,
                cust.FIRST_NAME as firstName,
                cust.LAST_NAME as lastName,
                cust.CITY as city,
                cust.COUNTRY as country,
                corder.ORDER_NUMBER as orderNumber,
                corder.TOTAL_AMOUNT as totalAmount
            FROM CUSTOMER cust LEFT JOIN CUSTOMER_ORDER corder
                 ON corder.CUSTOMER_ID = cust.ID
            WHERE
                 cust.FIRST_NAME = :firstName
``` 

you can use the CURL: http://localhost:8080/customers/~/search?firstname=Fran
to test the code. out.

If you see, the Query is getting the parameters from the Repository.  You can find the implementation of `Pageable` here: https://www.baeldung.com/spring-data-jpa-query

Hope this helps. Do reach out if you have any questions.

**Comment by huahuayu** [comment]
Hi thanks for gave feedback, I have went though it, but haven't try yet.
